### PR TITLE
fix: respect `.gitignore`

### LINKED ISSUE #126: When respecting gitignore, pattern negated in gitignore should take over wildcard.
With `"compareFolders.respectGitIgnore": true`
Given this .gitgnore:
```
a*
!a1.txt
```
then file a1.txt should not be ignored.

See https://github.com/moshfeu/vscode-compare-folders/pull/97 for previous discussion.

### PR DESCRIPTION
**Pull request by moshfeu**
resolve #126 following @gliviu's suggestion
continues the work at #97 

Additions

- use node 18 for globby
- `skipLibCheck` because globy's type check has failed

### CODE REVIEW

File: src/services/gitignoreFilter.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+  const isIgnoredLeft: GlobbyFilterFunction = isGitIgnoredSync({ cwd: pathLeft })
+  const isIgnoredRight: GlobbyFilterFunction = isGitIgnoredSync({ cwd: pathRight })
+
+  const gitignoreFilter: FilterHandler = (entry: Entry, relativePath: string, options: Options): boolean => {
+    const isIgnored: GlobbyFilterFunction = entry.origin === 'left' ? isIgnoredLeft : isIgnoredRight
+    // .git is not ignored by globby. We have to handle it.
+    if (entry.name === '.git') {
+      return false
+    }
+    console.log(2222, entry.absolutePath, isIgnored(entry.absolutePath))
```
Comment (gliviu) [inline src/services/gitignoreFilter.ts:26]: to be removed
